defmodule TcgSimulator.Repo.Migrations.AddCardTemplatesDecksMatches do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:matches, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :status, :text, null: false, default: "waiting"
      add :player1_id, :text, null: false
      add :player2_id, :text
      add :winner_id, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:matches, [:code], name: "matches_unique_code_index")

    create table(:decks, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:deck_cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :quantity, :bigint, null: false, default: 1

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :deck_id,
          references(:decks,
            column: :id,
            name: "deck_cards_deck_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :card_template_id, :uuid, null: false
    end

    create table(:card_templates, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:deck_cards) do
      modify :card_template_id,
             references(:card_templates,
               column: :id,
               name: "deck_cards_card_template_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:card_templates) do
      add :name, :text, null: false
      add :cost, :bigint, null: false, default: 0
      add :attack, :bigint, null: false, default: 0
      add :health, :bigint, null: false, default: 0

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:card_templates) do
      remove :updated_at
      remove :inserted_at
      remove :health
      remove :attack
      remove :cost
      remove :name
    end

    drop constraint(:deck_cards, "deck_cards_card_template_id_fkey")

    alter table(:deck_cards) do
      modify :card_template_id, :uuid
    end

    drop table(:card_templates)

    drop constraint(:deck_cards, "deck_cards_deck_id_fkey")

    drop table(:deck_cards)

    drop table(:decks)

    drop_if_exists unique_index(:matches, [:code], name: "matches_unique_code_index")

    drop table(:matches)
  end
end
